#!/usr/bin/env python3

import argparse
from pathlib import Path

from torch_npu.profiler.profiler import analyse


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Analyse Ascend profiling data generated by vLLM."
    )
    parser.add_argument(
        "profile_dir",
        nargs="?",
        type=Path,
        default=Path(__file__).resolve().parent / "vllm_profile",
        help="Directory containing generated *_ascend_pt folders.",
    )
    args = parser.parse_args()

    profile_dir = args.profile_dir.resolve()
    if not profile_dir.is_dir():
        raise SystemExit(f"Profiling directory does not exist: {profile_dir}")

    ascend_pt_dirs = sorted(
        path for path in profile_dir.glob("*_ascend_pt") if path.is_dir()
    )
    if not ascend_pt_dirs:
        raise SystemExit(f"No *_ascend_pt directory found under: {profile_dir}")

    for ascend_pt_dir in ascend_pt_dirs:
        print(f"Analysing: {ascend_pt_dir}")
        analyse(str(ascend_pt_dir))


if __name__ == "__main__":
    main()
