#!/usr/bin/env python3

import argparse
import os
import sys
from pathlib import Path

from torch_npu.profiler.profiler import analyse


REQUIRED_OUTPUTS = (
    "op_statistic.csv",
    "operator_details.csv",
    "kernel_details.csv",
    "step_trace_time.csv",
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Analyse Ascend profiling data generated by vLLM."
    )
    parser.add_argument(
        "--case",
        default=os.environ.get("PROFILE_CASE", "baseline_single_request"),
        help=(
            "Profiling case name under vllm_profile, for example "
            "bs32_prefill or bs32_decode."
        ),
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Analyse every profiling case under vllm_profile.",
    )
    parser.add_argument(
        "profile_dir",
        nargs="?",
        type=Path,
        default=None,
        help="Directory containing generated *_ascend_pt folders.",
    )
    args = parser.parse_args()

    profile_root = Path(__file__).resolve().parent / "vllm_profile"
    if args.profile_dir is not None:
        profile_dirs = [args.profile_dir.resolve()]
    elif args.all:
        profile_dirs = sorted(
            path for path in profile_root.iterdir() if path.is_dir()
        )
    else:
        profile_dirs = [profile_root / args.case]

    failures = []
    for profile_dir in profile_dirs:
        if not profile_dir.is_dir():
            raise SystemExit(f"Profiling directory does not exist: {profile_dir}")

        ascend_pt_dirs = sorted(
            path for path in profile_dir.glob("*_ascend_pt") if path.is_dir()
        )
        if not ascend_pt_dirs:
            raise SystemExit(f"No *_ascend_pt directory under: {profile_dir}")

        print(f"Analysing case: {profile_dir.name}")
        for ascend_pt_dir in ascend_pt_dirs:
            print(f"  Analysing: {ascend_pt_dir}")
            analyse(str(ascend_pt_dir))

            output_dir = ascend_pt_dir / "ASCEND_PROFILER_OUTPUT"
            missing = [
                name for name in REQUIRED_OUTPUTS if not (output_dir / name).is_file()
            ]
            if missing:
                failures.append(
                    f"{ascend_pt_dir}: missing {', '.join(missing)}"
                )

    if failures:
        print("\nProfiling analysis is incomplete:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
